name: Deploy Back-End Application on EC2

on:
  workflow_call:
  push:
    branches:
      [main]

jobs:
  build:
    uses: ./.github/workflows/starter.yml
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Deploy Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY_2 }}
          source: ./
          target: ${{ secrets.DIR_TARGET }}
