name: Deploy back-end aplication on EC2

on:
  push:
    branches:
      [main]

jobs:
  build:
    uses: ./.github/workflows/starter.yml
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Deploy Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./
          target: ${{ secrets.DIR_TARGET }}
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: mvn spring-boot:run