name: Deploy Back-End Application on EC2

on:
  workflow_call:
  push:
    branches:
      [develop]

jobs:
  build:
    uses: ./.github/workflows/starter.yml
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Deploy Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./
          target: ${{ secrets.DIR_TARGET }}
      - name: start server maven
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: mvn spring-boot:run